import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a professional Warranty Passport PDF
 * @param {Object} warranty - The warranty data object
 */
export const exportWarrantyPDF = async (warranty) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // --- Page 1: Structured Data ---

    // 1. Header with App Name & Title
    doc.setFillColor(192, 57, 43); // #C0392B (Brand Red)
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('WARRANTY PASSPORT', 20, 25);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Warranty Wallet', pageWidth - 70, 25);

    // 2. Product Title & Status
    doc.setTextColor(26, 26, 26);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(warranty.productName || 'Unknown Product', 20, 60);

    const status = warranty.status || 'ACTIVE';
    doc.setFontSize(10);
    if (status === 'EXPIRED') doc.setTextColor(231, 76, 60); // Red
    else if (status === 'EXPIRING_SOON') doc.setTextColor(230, 126, 34); // Orange
    else doc.setTextColor(46, 204, 113); // Green
    
    doc.text(`Status: ${status}`, 20, 68);

    // 3. Information Table
    const tableData = [
        ['Field', 'Information'],
        ['Brand / Merchant', warranty.merchantName || 'N/A'],
        ['Model Number', warranty.modelNumber || 'N/A'],
        ['Serial Number', warranty.serialNumber || 'N/A'],
        ['Invoice Number', warranty.invoiceNumber || 'N/A'],
        ['Purchase Date', warranty.invoiceDate || 'N/A'],
        ['Warranty Period', warranty.warrantyPeriod || 'N/A'],
        ['Price Paid', warranty.assetPrice || 'N/A'],
        ['Payment Method', warranty.paymentMethod || 'N/A'],
        ['Expiry Date', warranty.expiryDate || 'N/A'],
        ['Days Remaining', warranty.daysRemaining !== undefined ? `${warranty.daysRemaining} days` : 'N/A']
    ];

    autoTable(doc, {
        startY: 80,
        head: [tableData[0]],
        body: tableData.slice(1),
        theme: 'striped',
        headStyles: { fillColor: [192, 57, 43], textColor: 255 },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: 'bold', width: 50 } }
    });

    // 4. Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const footerY = pageHeight - 15;
    doc.text('This document is a digital summary of your original warranty bill.', 20, footerY);
    doc.text('Secure your assets with Warranty Wallet.', pageWidth - 80, footerY);

    // --- Page 2: Original Bill Image ---
    if (warranty.imagePath && warranty.imagePath.startsWith('http')) {
        try {
            const img = await loadImage(warranty.imagePath);
            doc.addPage();
            
            doc.setTextColor(26, 26, 26);
            doc.setFontSize(16);
            doc.setFont('helvetica', 'bold');
            doc.text('PROOF OF PURCHASE (ORIGINAL BILL)', 20, 20);
            
            // Calculate image aspect ratio to fit page
            const imgProps = doc.getImageProperties(img);
            const margin = 20;
            const maxWidth = pageWidth - (margin * 2);
            const maxHeight = pageHeight - (margin * 2) - 20;
            
            let imgWidth = imgProps.width;
            let imgHeight = imgProps.height;
            
            const ratio = Math.min(maxWidth / imgWidth, maxHeight / imgHeight);
            imgWidth *= ratio;
            imgHeight *= ratio;

            doc.addImage(img, 'JPEG', margin, 30, imgWidth, imgHeight);
        } catch (error) {
            console.error('Could not load bill image for PDF:', error);
        }
    }

    // Save PDF
    const productName = warranty.productName || 'Warranty';
    const filename = `${productName.replace(/\s+/g, '_')}_Warranty.pdf`;
    doc.save(filename);
};

/**
 * Helper to load an image into an HTML image element
 */
const loadImage = (url) => {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous'; // Required for CORS images (Cloudinary)
        img.onload = () => resolve(img);
        img.onerror = (e) => reject(e);
        img.src = url;
    });
};
